In [1]:
import numpy as np

In [3]:
#一维
a = np.array([0, 1, 2, 3 , 4])
b = np.array([0, 1, 2, 3 , 4])
print(a,type(a))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [9]:
#二维
c = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
print(c, type(c))
print(c.shape)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]] <class 'numpy.ndarray'>
(5, 5)


In [23]:
#三维
d = np.array([[(1.5, 2, 3), (4, 5, 6)],
              [(3, 2, 1), (4, 5, 6)]])
print(d, type(d))
print(d.shape)

[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]] <class 'numpy.ndarray'>
(2, 2, 3)


In [ ]:
# numpy中的array()和asarray()方法非常类似，他们都可以接受列表或数组类型的数据作为参数。
# 当他们的参数是列表型数据时，二者没有区别；当他们的参数是数组类型时，
# np.array()会返回参数数组的一个副本(copy,2者值一样但指向不同的内存),
# np.asarray()会返回参数数组的一个视图(2者指向同一块内存).

# 副本会新开辟一块内存，对于大数组来说，会存在大量的复制操作，
# 速度更慢且不节约内存；视图相当于新增加了一个指向当前内存的引用，
# 不存在复制操作，速度更快且节约内存，但是注意通过其中的一个引用修改数据，
# 其他引用的数据也会跟着变，因为他们指向同一块内存区域。


# array()仍然会 copy 出一个副本，占用新的内存，但不改变 dtype 时 asarray()不会。

In [15]:
#参数是列表时
x = [[1, 1, 1], [1, 1, 1], [1, 1, 1]]
print(x)
y = np.array(x)
print(y)
z = np.asarray(x)
x[1][2] = 2
print(x)
print(z)

[[1, 1, 1], [1, 1, 1], [1, 1, 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1, 1, 1], [1, 1, 2], [1, 1, 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [32]:
#参数是数组时, 
x = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
y = np.array(x)
z = np.asarray(x)
w = np.asarray(x, dtype=np.float)# 改变了数据类型 
x[1] = 2

print(x)
print(y)
print(z)
print(w)

[[1 1 1]
 [2 2 2]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [2 2 2]
 [1 1 1]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [50]:
# numpy的ndarry形式可能是Fortran-style 也可能是C-style，这两种数组的行与列的表述方式是相反的，
# 因为np.view（）是内存布局在数组上创建视图，导致输出dtype大小与内存中覆盖源数组的全长所需的字节数不完全匹配
# 解决办法:创建数组时a1 = np.asarray(a1, order='C')
# dtype属性的修改不可以直接进行，而应该借助于astype()方法
x = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
print(x, x.dtype)
# [[1 1 1]
#  [1 1 1]
#  [1 1 1]] int32
# x.dtype = np.float64
x.astype('float')

[[1 1 1]
 [1 1 1]
 [1 1 1]] int32


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
##zeros
# numpy.zeros(shape, dtype=float, order='C') 返回给定形状和类型的新数组，并用零填充。

# numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)
# Return an array of zeros with the same shape and type as a given array.

x = np.zeros(5)
print(x)
y = np.zeros([2, 3])
print(y)

z = np.array([[1, 2, 3],[4, 5, 6]])
print(z)
a = np.zeros_like(z)
print(a)


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [0 0 0]]


In [88]:
#ones  numpy.ones(shape, dtype=float, order='C') 返回给定形状和类型的新数组，并填充为1。
# numpy.ones(shape, dtype=float, order='C') 返回给定形状和类型的新数组，并填充为1。
# numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None) 
# Return an array of ones with the same shape and type as a given array.

x = np.ones(5)
print(x)
y = np.ones([4, 3])
print(y)
z = np.array([[1, 2, 3],[4, 5, 6]])
print(z)
b = np.ones_like(z)
print(b)


[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [1 1 1]]


In [105]:
#empty
# numpy.empty(shape, dtype=float, order='C') 返回一个空数组，数组元素为随机数。
# numpy.empty_like(prototype, dtype=None, order='K', subok=True, shape=None) 
# Return a new array with the same shape and type as a given array.

x = np.empty(4)
print(x)

y = np.empty([5,4])
print(y)

z = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[1, 3, 3]])
print(z)

c = np.empty_like(z)
print(c)


[9.90263869e+067 8.01304531e+262 2.60799828e-310 1.03341195e-311]
[[1.03389863e-311 6.27463370e-322 0.00000000e+000 0.00000000e+000]
 [1.11259940e-306 5.30276956e+180 1.57076922e-076 4.57664832e-071]
 [5.06479208e-086 3.35709490e-143 6.01433264e+175 6.93885958e+218]
 [5.56218858e+180 3.94356143e+180 4.79491204e-037 4.76095829e-038]
 [5.39366753e-066 9.50324206e-043 5.73635203e-143 1.50008929e+248]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 3 3]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 3 3]]


In [112]:
# numpy.full(shape, fill_value, dtype=None, order='C') 返回一个常数数组。
# numpy.full_like(a, fill_value, dtype=None, order='K', subok=True, shape=None)
# Return a full array with the same shape and type as a given array.

x = np.full((5,),7)
print(x)

y = np.full((5, 5), 6)
print(y)

z = np.array([[1, 2, 3], [4, 5, 6]])
d = np.full_like(z, 7)
print(d)

[7 7 7 7 7]
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]
[[7 7 7]
 [7 7 7]]


In [119]:
# numpy.eye(N, M=None, k=0, dtype=) 返回一个二维数组，对角线上为1，其他地方为零。
# numpy.identity(n, dtype=None)[source]
# Return the identity array,The identity array is a square array with ones on the main diagonal.

x = np.eye(6)
print(x)

x = np.eye(3, 4)
print(x)

x = np.identity(6)
print(x)





[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [129]:
# numpy.arange([start, ]stop, [step, ]dtype=None) 返回给定间隔内的均匀间隔的值。

# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None) 返回指定间隔内的等间隔数字。

# numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)返回数以对数刻度均匀分布。

# numpy.random.random(size=None) 返回一个由[0,1)内的随机数组成的数组。

a = np.arange(5)
print(a)
x = np.arange(2, 7, 2)
print(x)

x = np.linspace(start=0, stop=5, num=9)
print(x)

x = np.random.random(5)
print(x)

x = np.random.random([2, 3])
print(x)


[0 1 2 3 4]
[2 4 6]
[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375 5.   ]
[0.23434089 0.40810845 0.81973424 0.38972914 0.93755877]
[[0.19044867 0.15540893 0.55243688]
 [0.87707189 0.91785489 0.60974907]]


In [178]:
x = np.linspace(0, 1, 5)
print(x)

# #logspace中，开始点和结束点是10的幂

# x = np.logspace(0, 1, 5)
# print(np.around(x, 2))

x = [10 ** i for i in x]
print(np.around(x, 2))


[0.   0.25 0.5  0.75 1.  ]
[ 1.    1.78  3.16  5.62 10.  ]


In [180]:
# numpy.ndarray.ndim用于返回数组的维数（轴的个数）也称为秩，一维数组的秩为 1，二维数组的秩为 2，以此类推。

# numpy.ndarray.shape表示数组的维度，返回一个元组，这个元组的长度就是维度的数目，即 ndim 属性(秩)。

# numpy.ndarray.size数组中所有元素的总量，相当于数组的shape中所有元素的乘积，例如矩阵的元素总量为行与列的乘积。

# numpy.ndarray.dtype ndarray 对象的元素类型。

# numpy.ndarray.itemsize以字节的形式返回数组中每一个元素的大小。

import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a.shape)  # (5,)
print(a.dtype)  # int32
print(a.size)  # 5
print(a.ndim)  # 1
print(a.itemsize)  # 4

b = np.array([[1, 2, 3], [4, 5, 6.0]])
print(b.shape)  # (2, 3)
print(b.dtype)  # float64
print(b.size)  # 6
print(b.ndim)  # 2
print(b.itemsize)  # 8

(5,)
int32
5
1
4
(2, 3)
float64
6
2
8


In [181]:
# 在ndarray中所有元素必须是同一类型，否则会自动向下转换，int->float->str。

a = np.array([1, 2, 3, 4, 5])
print(a)  # [1 2 3 4 5]
b = np.array([1, 2, 3, 4, '5'])
print(b)  # ['1' '2' '3' '4' '5']
c = np.array([1, 2, 3, 4, 5.0])
print(c)  # [1. 2. 3. 4. 5.]


[1 2 3 4 5]
['1' '2' '3' '4' '5']
[1. 2. 3. 4. 5.]
